// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResp struct {
	ID       string `json:"id"`
	UserName string `json:"userName"`
}

type UserReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Name     string `json:"name"`
	HeadImg  string `json:"headImg"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
}
