// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "back_manage/service/sys/cmd/api/internal/handler/login"
	user "back_manage/service/sys/cmd/api/internal/handler/user"
	"back_manage/service/sys/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: login.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/add",
				Handler: user.UserHandler(serverCtx),
			},
		},
	)
}
