// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"back_manage/service/sys/cmd/api/internal/svc"
	"github.com/tal-tech/go-zero/rest"
	"net/http"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)
}
