// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "back_manage/service/sys/cmd/api/internal/handler/login"
	tenant "back_manage/service/sys/cmd/api/internal/handler/tenant"
	user "back_manage/service/sys/cmd/api/internal/handler/user"
	"back_manage/service/sys/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: login.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/add",
				Handler: user.CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/edit",
				Handler: user.EditUserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/tenant/add",
				Handler: tenant.CreateTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tenant/edit",
				Handler: tenant.EditTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tenant/setStatus",
				Handler: tenant.SetTenantStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tenant/getTenantPage",
				Handler: tenant.GetTenantPageHandler(serverCtx),
			},
		},
	)
}
